# Generated by Django 4.1 on 2022-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
